import * as THREE from './three.mjs';
import {buildKitchen} from './scene-option2.mjs';
const host=document.getElementById('alex-kitchen');
const viewport=host.querySelector('.kitchen-viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#f2efe8');
const model=buildKitchen();scene.add(model.root);
// Merge static geometry by material within visibility groups for responsive orbiting.
function mergeStatic(group){group.updateWorldMatrix(true,true);const inv=new THREE.Matrix4().copy(group.matrixWorld).invert();const buckets=new Map();group.traverse(o=>{if(!o.isMesh)return;let key=o.material.uuid;if(!buckets.has(key))buckets.set(key,{mat:o.material,geos:[]});let geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geo.applyMatrix4(new THREE.Matrix4().multiplyMatrices(inv,o.matrixWorld));buckets.get(key).geos.push(geo);});const lines=group.children.filter(o=>o.isLine);group.clear();group.add(...lines);for(const {mat,geos} of buckets.values()){let g=new THREE.BufferGeometry();for(const name of ['position','normal','uv']){let size=name==='uv'?2:3,total=geos.reduce((n,g)=>n+(g.attributes[name]?.array.length||0),0);if(!total)continue;let a=new Float32Array(total),offset=0;for(let geo of geos){let b=geo.attributes[name]?.array;if(b){a.set(b,offset);offset+=b.length;}}g.setAttribute(name,new THREE.BufferAttribute(a,size));}let m=new THREE.Mesh(g,mat);m.castShadow=true;m.receiveShadow=true;group.add(m);}}
model.root.updateMatrixWorld(true);model.root.attach(model.doorPivot);
model.doorPivot.rotation.y = 0;
model.root.attach(model.dwPivot);model.root.attach(model.cornerFronts);for(const g of Object.values(model.groups))mergeStatic(g);
const perspective=new THREE.PerspectiveCamera(43,1,.03,60);const ortho=new THREE.OrthographicCamera(-3,3,1.9,-1.9,.03,60);let camera=perspective;
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.98;renderer.outputColorSpace=THREE.SRGBColorSpace;viewport.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Three-dimensional kitchen coordination model. Drag to orbit and use the mouse wheel to zoom.');renderer.domElement.setAttribute('role','img');
scene.add(new THREE.HemisphereLight('#ffffff','#c4beb1',1.65));
const key=new THREE.DirectionalLight('#fff4df',2.6);key.position.set(-2.5,5,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-4,right:4,top:5,bottom:-4,near:.1,far:15});key.shadow.bias=-.0006;key.shadow.normalBias=.012;key.shadow.radius=3;scene.add(key);key.target.position.set(1,1,1.4);scene.add(key.target);
const fill=new THREE.DirectionalLight('#d4e6ff',.85);fill.position.set(-2,2,-1);scene.add(fill);
for(const [x,z] of [[.7,.55],[1.6,1.6],[1.25,2.6]]){let l=new THREE.PointLight('#ffdfad',.25,2.2,2);l.position.set(x,1.52,z);scene.add(l);}
const overlay=host.querySelector('.dimension-overlay'),ctx=overlay.getContext('2d');
let target=new THREE.Vector3(1.02,1.20,1.45),radius=6.0,az=-Math.PI/2,el=.35,showDims=false,showUppers=true,drag=null,tour=false,last=0,view='overview';
function setView(name){tour=false;host.querySelector('[data-action=tour]').setAttribute('aria-pressed','false');view=name;camera=name==='plan'?ortho:perspective;showDims=name==='plan'||name==='ac';showUppers=name!=='plan';if(name==='overview'){target.set(1.05,1.23,1.475);radius=5.8;az=-Math.PI/2;el=.36;camera.fov=43;}if(name==='sink'){target.set(1.15,1.25,2.75);radius=1.45;az=-Math.PI+.10;el=.16;camera.fov=85;}if(name==='cooker'){target.set(1.94,1.38,1.52);radius=2.00;az=-Math.PI/2;el=.13;camera.fov=77;}if(name==='fridge'){target.set(1.02,1.39,.1);radius=2.45;az=-.12;el=.04;camera.fov=64;}if(name==='ac'){target.set(.12,2.03,1.075);radius=1.32;az=Math.PI/2;el=.04;camera.fov=67;}if(name==='plan'){target.set(1.1,0,1.475);radius=5.5;az=0;el=1.568;camera.fov=43;}camera.updateProjectionMatrix();host.querySelector('[data-action=uppers]').setAttribute('aria-pressed',String(showUppers));host.querySelector('[data-action=dims]').setAttribute('aria-pressed',String(showDims));for(const b of host.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===name));draw();}
function dimensions(){ctx.clearRect(0,0,overlay.width,overlay.height);if(!showDims)return;const W=viewport.clientWidth,H=viewport.clientHeight;ctx.font='500 13px system-ui';ctx.direction='ltr';ctx.textAlign='center';ctx.textBaseline='middle';function project(a){let p=new THREE.Vector3(...a).project(camera);return [(p.x+1)*W/2,(1-p.y)*H/2];}function line(a,b,text){let A=project(a),B=project(b);ctx.strokeStyle='#46555c';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(...A);ctx.lineTo(...B);ctx.stroke();let dx=B[0]-A[0],dy=B[1]-A[1],len=Math.hypot(dx,dy);if(len<1)return;let nx=-dy/len*5,ny=dx/len*5;for(let p of [A,B]){ctx.beginPath();ctx.moveTo(p[0]-nx,p[1]-ny);ctx.lineTo(p[0]+nx,p[1]+ny);ctx.stroke();}let x=(A[0]+B[0])/2,y=(A[1]+B[1])/2;ctx.fillStyle='#f8f6ef';let w=ctx.measureText(text).width+12;ctx.fillRect(x-w/2,y-10,w,20);ctx.fillStyle='#233a46';ctx.fillText(text,x,y);}
if(view==='ac'){line([.24,2.38,.675],[.24,2.38,1.475],'AC 80 cm');return;}line([0,.06,-.22],[2.21,.06,-.22],'2.21 m');line([2.52,.06,0],[2.52,.06,2.95],'2.95 m');line([0,.065,3.14],[2.01,.065,3.14],'2.01 m');if(view==='plan'){line([1.48,.08,1.2],[1.48,.08,2.1],'90 cm');line([0,.08,3.0],[.60,.08,3.0],'Storage');line([.63,.08,3.0],[1.38,.08,3.0],'Sink 75');line([-.12,.08,.70],[-.12,.08,1.45],'Entry 75');}}
function draw(){const w=viewport.clientWidth,h=viewport.clientHeight;if(renderer.domElement.width!==Math.floor(w*renderer.getPixelRatio())||renderer.domElement.height!==Math.floor(h*renderer.getPixelRatio())){renderer.setSize(w,h);overlay.width=w;overlay.height=h;camera.aspect=w/h;camera.updateProjectionMatrix();}if(camera===ortho){const hh=1.92*(radius/5.5);camera.left=-hh*w/h;camera.right=hh*w/h;camera.top=hh;camera.bottom=-hh;camera.updateProjectionMatrix();}camera.position.set(target.x+radius*Math.sin(az)*Math.cos(el),target.y+radius*Math.sin(el),target.z+radius*Math.cos(az)*Math.cos(el));camera.lookAt(target);model.groups.west.visible=camera.position.x>0&&view!=='plan';model.groups.upper.visible=showUppers;model.groups.north.visible=camera.position.z>-.01&&view!=='plan';model.groups.south.visible=camera.position.z<2.95&&view!=='plan';model.groups.east.visible=camera.position.x<2.21&&view!=='plan';renderer.render(scene,camera);dimensions();}
let doorOpen=false;host.querySelector('[data-action=door]').onclick=e=>{doorOpen=!doorOpen;model.doorPivot.rotation.y=doorOpen ? -Math.PI/2 : 0;e.currentTarget.setAttribute('aria-pressed',String(doorOpen));host.querySelector('.door-status').textContent=doorOpen?'90° swing shown. Verify appliance clearances and access to the prep corner before approval.':'Refrigerator at entry corner · entry projection accepted for this study';draw();};
for(const b of host.querySelectorAll('[data-view]'))b.onclick=()=>setView(b.dataset.view);
host.querySelector('[data-action=uppers]').onclick=e=>{showUppers=!showUppers;e.currentTarget.setAttribute('aria-pressed',String(showUppers));draw();};host.querySelector('[data-action=dims]').onclick=e=>{showDims=!showDims;e.currentTarget.setAttribute('aria-pressed',String(showDims));draw();};host.querySelector('[data-action=tour]').onclick=e=>{tour=!tour;e.currentTarget.setAttribute('aria-pressed',String(tour));if(tour){camera=perspective;last=0;view='tour';showUppers=true;showDims=false;target.set(1.1,1.1,1.475);radius=5.8;el=.4;camera.fov=43;camera.updateProjectionMatrix();requestAnimationFrame(animate);}};
function animate(t){if(!tour)return;if(last)az+=(t-last)*.00015;last=t;draw();requestAnimationFrame(animate);}
renderer.domElement.addEventListener('pointerdown',e=>{tour=false;last=0;host.querySelector('[data-action=tour]').setAttribute('aria-pressed','false');drag={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;az-=(e.clientX-drag.x)*.006;el=Math.max(-.05,Math.min(1.57,el+(e.clientY-drag.y)*.006));drag={x:e.clientX,y:e.clientY};draw();});renderer.domElement.addEventListener('pointerup',()=>drag=null);renderer.domElement.addEventListener('pointercancel',()=>drag=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();radius=Math.max(.65,Math.min(10,radius*Math.exp(e.deltaY*.001)));draw();},{passive:false});
new ResizeObserver(draw).observe(viewport);setView('overview');host.querySelector('.load-status').textContent='Drag to orbit · mouse wheel to zoom';

let dwOpen=false;host.querySelector('[data-action=dw]').onclick=e=>{dwOpen=!dwOpen;model.dwPivot.rotation.x=dwOpen?Math.PI/2:0;e.currentTarget.setAttribute('aria-pressed',String(dwOpen));draw();};host.querySelector('[data-action=corners]').onclick=e=>{model.cornerFronts.visible=!model.cornerFronts.visible;e.currentTarget.setAttribute('aria-pressed',String(!model.cornerFronts.visible));draw();};
